### PR TITLE
I have created travel blog site

### PR DESCRIPTION
**Pull request by mifrasgaffoor**
*Travel Blog Site Using HTML,CSS

Preview
image

image

image

image

### CODE REVIEW

**Comment by simranquirky** [comment]
This pull request contain the weather app files as well can u remove it. And also keep the folder name short travel_blog

**Comment by mifrasgaffoor** [comment]
@simranquirky  how can I do remove it could you help me?
This is my very first time PR and These things

**Comment by simranquirky** [comment]
To delete a file :  https://docs.github.com/en/repositories/working-with-files/managing-files/deleting-files-in-a-repository#deleting-a-file

You will have to delete the files inside weather folder. And upload the travel blog site files inside travel_blog -> travel_blog1 folder.

**Comment by mifrasgaffoor** [comment]
image

after clicking the weather folder 
image


then how can I remove it I have a little bit confused

**Comment by simranquirky** [comment]
Check this : https://youtu.be/HGmUV8N2XoQ

**Comment by simranquirky** [comment]
If you still find it difficult just attach the previously uploaded files of travel blog site . I will first merge your request and then delete the required files on my own . Hope you are ok with it @mifrasgaffoor

**Comment by mifrasgaffoor** [comment]
@simranquirky yah I have uploaded cloud check it 

Thanks a lot for your guidance and value replies

**Review by simranquirky — APPROVED** [review]

**Pull request merged**
